/* =========================================================
   INIT DATABASE – UberEats-like system (MySQL 8.x)
   Koszyk = ZAMOWIENIE.ID_STATUS IS NULL
   ========================================================= */

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ZAMOWIENIE_ITEM;
DROP TABLE IF EXISTS ZAMOWIENIE;
DROP TABLE IF EXISTS MENU_ITEM;
DROP TABLE IF EXISTS RESTAURACJA;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS KAT_TYP_DANIA;
DROP TABLE IF EXISTS KAT_PLATNOSC;
DROP TABLE IF EXISTS KAT_STATUS_ZAMOWIENIA;
DROP TABLE IF EXISTS KAT_STATUS_DOSTAWY;

DROP TRIGGER IF EXISTS TRG_ONE_OPEN_CART;

SET FOREIGN_KEY_CHECKS = 1;

-- =========================================================
-- SŁOWNIKI
-- =========================================================

CREATE TABLE ROLE (
    ID_ROLA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE,
    AKTYWNA CHAR(1) DEFAULT 'Y' CHECK (AKTYWNA IN ('Y','N'))
) ENGINE=InnoDB;

CREATE TABLE KAT_STATUS_ZAMOWIENIA (
    ID_STATUS BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAZWA VARCHAR(100) NOT NULL UNIQUE,
    AKTYWNA CHAR(1) DEFAULT 'Y' CHECK (AKTYWNA IN ('Y','N'))
) ENGINE=InnoDB;

CREATE TABLE KAT_STATUS_DOSTAWY (
    ID_STATUS BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAZWA VARCHAR(100) NOT NULL UNIQUE,
    AKTYWNA CHAR(1) DEFAULT 'Y' CHECK (AKTYWNA IN ('Y','N'))
) ENGINE=InnoDB;

CREATE TABLE KAT_PLATNOSC (
    ID_PLATNOSC BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE,
    AKTYWNA CHAR(1) DEFAULT 'Y' CHECK (AKTYWNA IN ('Y','N'))
) ENGINE=InnoDB;

CREATE TABLE KAT_TYP_DANIA (
    ID_TYP_DANIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAZWA VARCHAR(100) NOT NULL UNIQUE,
    AKTYWNA CHAR(1) DEFAULT 'Y' CHECK (AKTYWNA IN ('Y','N'))
) ENGINE=InnoDB;

-- =========================================================
-- UŻYTKOWNICY
-- =========================================================

CREATE TABLE USER (
    ID_USER BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    AKTYWNY CHAR(1) DEFAULT 'Y' CHECK (AKTYWNY IN ('Y','N')),
    DATA_DODANIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE USER_ROLE (
    ID_USER BIGINT NOT NULL,
    ID_ROLA BIGINT NOT NULL,
    PRIMARY KEY (ID_USER, ID_ROLA),
    CONSTRAINT FK_UR_USER FOREIGN KEY (ID_USER)
        REFERENCES USER(ID_USER),
    CONSTRAINT FK_UR_ROLA FOREIGN KEY (ID_ROLA)
        REFERENCES ROLE(ID_ROLA)
) ENGINE=InnoDB;

-- =========================================================
-- RESTAURACJE I MENU
-- =========================================================

CREATE TABLE RESTAURACJA (
    ID_RESTAURACJI BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAZWA VARCHAR(200) NOT NULL,
    ADRES VARCHAR(300),
    AKTYWNA CHAR(1) DEFAULT 'Y' CHECK (AKTYWNA IN ('Y','N'))
) ENGINE=InnoDB;

CREATE TABLE MENU_ITEM (
    ID_MENU_ITEM BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_RESTAURACJI BIGINT NOT NULL,
    NAZWA VARCHAR(200) NOT NULL,
    CENA DECIMAL(10,2) NOT NULL CHECK (CENA > 0),
    ID_TYP_DANIA BIGINT,
    AKTYWNY CHAR(1) DEFAULT 'Y' CHECK (AKTYWNY IN ('Y','N')),
    CONSTRAINT FK_MI_REST FOREIGN KEY (ID_RESTAURACJI)
        REFERENCES RESTAURACJA(ID_RESTAURACJI),
    CONSTRAINT FK_MI_TYP FOREIGN KEY (ID_TYP_DANIA)
        REFERENCES KAT_TYP_DANIA(ID_TYP_DANIA)
) ENGINE=InnoDB;

-- =========================================================
-- ZAMÓWIENIA (KOSZYK = ID_STATUS IS NULL)
-- =========================================================

CREATE TABLE ZAMOWIENIE (
    ID_ZAMOWIENIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_KLIENTA BIGINT NOT NULL,
    ID_RESTAURACJI BIGINT NOT NULL,

    ID_STATUS BIGINT NULL,
    ID_PLATNOSC BIGINT NULL,
    ADRES_DOSTAWY VARCHAR(300),

    KOSZT_DOSTAWY DECIMAL(10,2),
    KWOTA_CALKOWITA DECIMAL(10,2),

    DATA_UTWORZENIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ZAM_KLIENT FOREIGN KEY (ID_KLIENTA)
        REFERENCES USER(ID_USER),

    CONSTRAINT FK_ZAM_REST FOREIGN KEY (ID_RESTAURACJI)
        REFERENCES RESTAURACJA(ID_RESTAURACJI),

    CONSTRAINT FK_ZAM_STATUS FOREIGN KEY (ID_STATUS)
        REFERENCES KAT_STATUS_ZAMOWIENIA(ID_STATUS),

    CONSTRAINT FK_ZAM_PLAT FOREIGN KEY (ID_PLATNOSC)
        REFERENCES KAT_PLATNOSC(ID_PLATNOSC),

    CONSTRAINT CHK_ZAM_STATUS_DATA CHECK (
        ID_STATUS IS NULL OR
        (
            ID_PLATNOSC IS NOT NULL AND
            ADRES_DOSTAWY IS NOT NULL AND
            KWOTA_CALKOWITA IS NOT NULL
        )
    )
) ENGINE=InnoDB;

CREATE TABLE ZAMOWIENIE_ITEM (
    ID_ZAMOWIENIE_ITEM BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_ZAMOWIENIA BIGINT NOT NULL,
    ID_MENU_ITEM BIGINT NOT NULL,
    ILOSC INT NOT NULL CHECK (ILOSC > 0),
    CENA_SZTUKA DECIMAL(10,2) NOT NULL CHECK (CENA_SZTUKA > 0),
    CENA_RAZEM DECIMAL(10,2) NOT NULL CHECK (CENA_RAZEM > 0),
    CONSTRAINT FK_ZI_ZAM FOREIGN KEY (ID_ZAMOWIENIA)
        REFERENCES ZAMOWIENIE(ID_ZAMOWIENIA),
    CONSTRAINT FK_ZI_MI FOREIGN KEY (ID_MENU_ITEM)
        REFERENCES MENU_ITEM(ID_MENU_ITEM)
) ENGINE=InnoDB;

-- =========================================================
-- TRIGGER: JEDEN AKTYWNY KOSZYK
-- =========================================================

DELIMITER $$

CREATE TRIGGER TRG_ONE_OPEN_CART
BEFORE INSERT ON ZAMOWIENIE
FOR EACH ROW
BEGIN
    DECLARE v_count INT;

    IF NEW.ID_STATUS IS NULL THEN
        SELECT COUNT(*)
        INTO v_count
        FROM ZAMOWIENIE
        WHERE ID_KLIENTA = NEW.ID_KLIENTA
          AND ID_STATUS IS NULL;

        IF v_count > 0 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Użytkownik może mieć tylko jeden aktywny koszyk';
        END IF;
    END IF;
END$$

DELIMITER ;

-- =========================================================
-- INIT DATA
-- =========================================================

INSERT INTO ROLE (NAZWA) VALUES ('ADMIN');
INSERT INTO ROLE (NAZWA) VALUES ('KLIENT');
INSERT INTO ROLE (NAZWA) VALUES ('DOSTAWCA');

INSERT INTO KAT_STATUS_ZAMOWIENIA (NAZWA) VALUES ('ZLOZONE');
INSERT INTO KAT_STATUS_ZAMOWIENIA (NAZWA) VALUES ('OPLACONE');
INSERT INTO KAT_STATUS_ZAMOWIENIA (NAZWA) VALUES ('W_REALIZACJI');
INSERT INTO KAT_STATUS_ZAMOWIENIA (NAZWA) VALUES ('DOSTARCZONE');
INSERT INTO KAT_STATUS_ZAMOWIENIA (NAZWA) VALUES ('ANULOWANE');

INSERT INTO KAT_STATUS_DOSTAWY (NAZWA) VALUES ('PRZYJETA');
INSERT INTO KAT_STATUS_DOSTAWY (NAZWA) VALUES ('W_DRODZE');
INSERT INTO KAT_STATUS_DOSTAWY (NAZWA) VALUES ('DOSTARCZONA');

INSERT INTO KAT_PLATNOSC (NAZWA) VALUES ('KARTA');
INSERT INTO KAT_PLATNOSC (NAZWA) VALUES ('BLIK');
INSERT INTO KAT_PLATNOSC (NAZWA) VALUES ('GOTOWKA');

COMMIT;
